(deftheme jake
  "Created 2023-04-29.")

(custom-theme-set-faces
 'jake
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#1D252C" :foreground "#A0B3C5" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 105 :width normal :foundry "GOOG" :family "Berkeley Mono"))))
 '(cursor ((t (:background "#5EC4FF"))))
 '(fixed-pitch ((t (:slant normal :weight normal :height 105 :width normal :foundry "GOOG" :family "Berkeley Mono"))))
 '(variable-pitch ((t (:slant normal :weight normal :height 105 :width normal :foundry "GOOG" :family "Noto Sans"))))
 '(escape-glyph ((t (:foreground "#70E1E8"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#5EC4FF"))))
 '(highlight ((t (:foreground "#10151C" :background "#5EC4FF"))))
 '(region ((t (:extend t :background "#28323B"))))
 '(shadow ((t (:foreground "#56697A"))))
 '(secondary-selection ((t (:extend t :background "#41505E"))))
 '(trailing-whitespace ((t (:background "#D95468"))))
 '(font-lock-builtin-face ((t (:foreground "#5EC4FF"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#41505E"))))
 '(font-lock-constant-face ((t (:foreground "#E27E8D"))))
 '(font-lock-doc-face ((t (:foreground "#707b86" :inherit (font-lock-comment-face)))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:foreground "#33CED8"))))
 '(font-lock-keyword-face ((t (:foreground "#5EC4FF"))))
 '(font-lock-negation-char-face ((t (:foreground "#5EC4FF" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:foreground "#5EC4FF" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#5EC4FF" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#5EC4FF" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#539AFC"))))
 '(font-lock-type-face ((t (:foreground "#EBBF83"))))
 '(font-lock-variable-name-face ((t (:foreground "#718CA1"))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#5EC4FF"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#384551" :inherit (default)))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((t (:foreground "#A0B3C5" :background "#181E24"))))
 '(mode-line ((t (:box nil :background "#181f25"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#5EC4FF"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#56697A" :background "#1D252C"))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#10151C" :background "#D95468"))))
 '(lazy-highlight ((t (:foreground "#10151C" :background "#30546b"))))
 '(match ((t (:weight bold :foreground "#8BD49C" :background "#10151C"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'jake)
